project_id = "zuxikzoyzuiyldbtlsdm"

[functions.check-telegram-channel]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.notify-new-application]
verify_jwt = false

[functions.notify-application-result]
verify_jwt = false

[functions.notify-partners-new-order]
verify_jwt = false

[functions.notify-partners-new-question]
verify_jwt = false
