project_id = "kbjeggprymvkxhfnahxc"

[functions.publish-partner-to-channel]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.geocode-city]
verify_jwt = false

[functions.test-notification]
verify_jwt = false