project_id = "ishzwulmiixtuouisdyw"

[functions.check-telegram-channel]
verify_jwt = false

[functions.geocode-city]
verify_jwt = false

[functions.geocode-address]
verify_jwt = false

[functions.publish-partner-to-channel]
verify_jwt = false
